"""Report generation: Markdown for in-UI rendering, plain text for downloads.

Downloads use ``tempfile`` so they don't accumulate in the working directory
across sessions (the previous approach implied by the saved
``ppe_report_*.txt`` would have leaked files over time).
"""
from __future__ import annotations

import tempfile
from datetime import datetime

from config import COMPLIANCE_EXCELLENT_PCT, COMPLIANCE_WARNING_PCT
from detection import ComplianceSummary, Detection


def _status_label(rate: float | None) -> tuple[str, str]:
    """Return (emoji, label) for a compliance rate. ``None`` means there
    were no PPE-relevant detections in the frame."""
    if rate is None:
        return "⚪", "NO PPE-RELEVANT DETECTIONS"
    if rate >= COMPLIANCE_EXCELLENT_PCT:
        return "✅", "EXCELLENT"
    if rate >= COMPLIANCE_WARNING_PCT:
        return "⚠️", "NEEDS ATTENTION"
    return "🚨", "CRITICAL"


def _format_rate(rate: float | None) -> str:
    return f"{rate:.0f}%" if rate is not None else "N/A"


def render_markdown(
    detections: list[Detection],
    summary: ComplianceSummary,
    inference_time: float,
) -> str:
    """Render a Markdown compliance report for in-UI display."""
    if not detections:
        return (
            "No detections above the confidence threshold. "
            "Try lowering the threshold."
        )

    emoji, label = _status_label(summary.compliance_rate)
    rate_str = _format_rate(summary.compliance_rate)

    lines: list[str] = [
        f"## {emoji} Compliance Score: {rate_str} — {label}",
        "",
        f"**Scan completed in {inference_time:.2f}s**",
        "",
        "---",
        "",
        "### Summary",
        "",
        "| Category | Count |",
        "|----------|-------|",
        f"| ✅ Proper PPE | {summary.safe} |",
        f"| 🚨 Violations | {summary.violations} |",
        f"| ℹ️ Context (person, cone, machinery, vehicle) | {summary.context} |",
        f"| **Total Detections** | **{summary.total}** |",
        "",
        "---",
        "",
        "### Detailed Findings",
        "",
    ]

    grouped: list[tuple[str, list[Detection]]] = [
        ("🚨 Violations", [d for d in detections if d.status == "violation"]),
        ("✅ Proper PPE", [d for d in detections if d.status == "safe"]),
        ("ℹ️ Context", [d for d in detections if d.status == "context"]),
    ]
    for header, group in grouped:
        if not group:
            continue
        lines.append(f"**{header}:**")
        for d in group:
            lines.append(f"- {d.class_name} (confidence: {d.confidence:.0%})")
        lines.append("")
    return "\n".join(lines)


def render_text(
    detections: list[Detection],
    summary: ComplianceSummary,
    inference_time: float,
) -> str:
    """Render a plain-text compliance report suitable for download/archive."""
    if not detections:
        return "No detections above the confidence threshold.\n"

    _, label = _status_label(summary.compliance_rate)
    rate_str = _format_rate(summary.compliance_rate)
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    border = "=" * 50

    lines: list[str] = [
        "PPE COMPLIANCE REPORT",
        "Generated by PPE Compliance Detector",
        border,
        "",
        f"SCAN TIME:      {timestamp}",
        f"INFERENCE TIME: {inference_time:.2f}s",
        f"COMPLIANCE:     {rate_str} - {label}",
        "",
        border,
        "SUMMARY",
        border,
        f"Proper PPE:    {summary.safe}",
        f"Violations:    {summary.violations}",
        f"Context:       {summary.context}",
        f"Total:         {summary.total}",
        "",
        border,
        "DETAILED FINDINGS",
        border,
        "",
    ]

    grouped: list[tuple[str, list[Detection]]] = [
        ("VIOLATIONS", [d for d in detections if d.status == "violation"]),
        ("PROPER PPE", [d for d in detections if d.status == "safe"]),
        ("CONTEXT", [d for d in detections if d.status == "context"]),
    ]
    for header, group in grouped:
        if not group:
            continue
        lines.append(f"{header}:")
        for d in group:
            lines.append(f"  - {d.class_name} ({d.confidence:.0%} confidence)")
        lines.append("")
    return "\n".join(lines)


def write_report_tempfile(text: str) -> str:
    """Write ``text`` to a tempfile and return its path.

    Uses ``tempfile.NamedTemporaryFile(delete=False)`` so Gradio can serve
    the path to the client; the OS cleans up the temp directory in time.
    The file is prefixed with a human-readable timestamp for clarity.
    """
    prefix = f"ppe_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}_"
    fd = tempfile.NamedTemporaryFile(
        mode="w",
        suffix=".txt",
        prefix=prefix,
        delete=False,
        encoding="utf-8",
    )
    try:
        fd.write(text)
    finally:
        fd.close()
    return fd.name
